name: Flask API Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Flask server (with a timeout to prevent the job from running indefinitely)
    - name: Run Flask server
      run: |
        nohup python app.py &  # Run Flask in the background
        sleep 5  # Give Flask time to start
        curl http://127.0.0.1:5000  # Make a request to the server
